### PR TITLE
New old new old new waitlist design (original design, new version)

### PR DESCRIPTION
**Pull request by Leo-MathGuy**
Remade, looks mostly the same. Completely responsive, to giant screens to 150px width nokia.

The 3 boxes work fine, and added better things with js which disables auto-back when <600px
Used scrolltrigger to add some animations

### CODE REVIEW

**Comment by Leo-MathGuy** [comment]
#67

**Comment by Leo-MathGuy** [comment]
before you merge actually look at the page ok?

**Comment by Leo-MathGuy** [comment]
Also, I want at least one review then I'll do you you want and then merge ok

**Comment by Leo-MathGuy** [comment]
So don't merge it yourself

**Comment by Leo-MathGuy** [comment]
And actually **review**

**Review by srivatsav-kannan — CHANGES_REQUESTED** [review]
Make the gaps smaller. Use the new discord logo. In the footer move the aviquo logo all the way to the right. In fact make the footer exactly as it way before this. Add the arrows that are currently there, rework their functionality if u want.

**Comment by Leo-MathGuy** [comment]
1. What gaps?
2. It looks worse in my opinion and we want it to be more memorable
3. Why arrows, the hover "sticks" for 2 seconds

**Comment by Leo-MathGuy** [comment]
We only have 3 boxes and they are all visible why arrows

**Comment by Leo-MathGuy** [comment]
> Make the gaps smaller. Use the new discord logo. In the footer move the aviquo logo all the way to the right. In fact make the footer exactly as it way before this. Add the arrows that are currently there, rework their functionality if u want.

**Comment by srivatsav-kannan** [comment]
> * What gaps?
> * It looks worse that way in my opinion and we want it to be more memorable (the logo)
> * Why arrows, the hover "sticks" for 2 seconds

The massive gaps between sections, tone em down a little. No it looks better. We'll talk about the arrows later.

**Comment by Leo-MathGuy** [comment]
Ale you know what I'm redoing the entire color scheme for the gradient to be less purple the whole website is purple it's not how a landing page works

**Comment by srivatsav-kannan** [comment]
bring back the old footer
make it responsive
redesign hero section

**Pull request closed without merging**
